# metadata_url: "https://storage.googleapis.com/public-datasets-mswc/metadata.json.gz"
en_embeddings_url: "https://drive.google.com/uc?id=1aoOWzmxBCvSqaXEovTIYB1oaDySN44Ci"
id_embeddings_url: "https://drive.google.com/uc?id=1wg0t2XXMOBTpEani9-2r1xOez57Weynl"
pt_embeddings_url: "https://drive.google.com/uc?id=1hMt5jKA98hN6kv0gwOT-PBNGehYheYAo"
# dataset_url: "https://storage.googleapis.com/public-datasets-mswc/mswc_microset.tar.gz"

